apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-voting-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/emesonbright/example-voting-app.git'
    targetRevision: main
    path: k8s-specifications/games  # Ensure this path is relative
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

